name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  # Test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
    
  #   - name: Checkout 
  #     uses: actions/checkout@v3
      
  #   - name: Node
  #     uses: actions/setup-node@v3
  #     with:
  #       cache: 'npm'
        
  #   - name: Test
  #     run: |
  #       npm install
  #       npm run test-cloud

  Build:
    name: Build
    # needs: Test
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: |
          docs

  copy:
    needs: Build
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: |
            docs
            
      - shell: bash
        run: |
          ls -alt

      - name: copy
        env:
          SRC_FOLDER_PATH: 'docs'
          TARGET_BRANCH: 'deploy'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote update
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          ls -alt
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
          